### ISSUE TITLE
Namespace overlap with Dalton Maag's InterFace font family

### ISSUE THREAD

**Issue by codeman38** [rsms/interface#15]
Since CSS font matching is case-insensitive, this font's naming could potentially be troublesome if someone is also embedding Dalton Maag's "InterFace" font family or has it installed.

See, for instance, the recommended CSS on [the Typekit page for the Dalton Maag font](https://typekit.com/fonts/interface/details/interface-regular):

```
font-family: interface, sans-serif;
font-style: normal;
font-weight: 400;
```

**Comment by rsms** [comment]
When using fonts in CSS, you can assign it any name you want in the `@font-face` declaration.

For instance,  you might do this:

```css
@font-face {
  font-family: 'interface1';
  font-style:  normal;
  font-weight: 400;
  src: url("fonts/Interface1.woff2") format("woff2");
}
@font-face {
  font-family: 'interface2';
  font-style:  normal;
  font-weight: 400;
  src: url("fonts/Interface1.woff2") format("woff2");
}
.a { font-family: interface1; }
.b { font-family: interface2; }
```
